services:
  php:
    build:
      context: ./ # Path to Dockerfile.
    ports:
      - "8000:80" # Port binding.
    volumes:
      - .:/var/www/html # The volume to bind.
    command: >
      bash -c "composer install --no-dev --optimize-autoloader && php -S 0.0.0.0:80"